title: "Event Store Documentation"
url: "http://docs.geteventstore.com"
permalink: pretty
markdown: redcarpet
highlighter: pygments

top_level_sections:
    - Introduction
    - Server
    - .NET API
    - HTTP API

defaults:
    -
        scope:
            path: ""
        values:
            exclude_from_sidebar: false
            layout: "docs"
            pinned: false
