title: "Event Store Documentation"
url: "http://docs.geteventstore.com"
permalink: pretty
markdown: redcarpet
highlighter: pygments

top_level_sections:
    - Introduction
    - Server
    - .NET API
    - HTTP API

latest_versions:
    server: 3.0.1
    dotnet-api: 3.0.1
    http-api: 3.0.1

defaults:
    -
        scope:
            path: ""
        values:
            exclude_from_sidebar: false
            layout: "docs"
            pinned: false
