title: "Event Store Documentation"
url: "http://docs.geteventstore.com"
permalink: pretty
markdown: redcarpet
highlighter: pygments

defaults:
    -
        values:
            layout: "docs"
            exclude_from_sidebar: false